import './globals.css'
import { Roboto } from 'next/font/google'
import Header from '@/src/components/Header'

const roboto = Roboto({ 
  weight: ['400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>

      </head>
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
